### ISSUE TITLE
Feature 43: Add extension checking to UploadForm

### ISSUE THREAD

**Issue by wittekip** [opencirclesolutions/dynamo#43]
Add the option to specify that only certain file extensions can be uploaded using the UploadForm component.

**Comment by OpenCircleEndy** [comment]
The standard Vaadin Upload component has no support for such a filter. As the browser window, the dialog in which you can select the files, is not part of the web application the options are limited. There is a possibility to set an 'accept' attribute on the file upload html element. This will instruct the browser dialog to set an 'alternative files' filter. This seems to work at least in Chrome and Windows 7.
[See stackoverflow](http://stackoverflow.com/questions/4328947/limit-file-format-when-using-input-type-file)

To accommodate the developer we could define our own upload form which you could configured the allowed mime-types. Then override the default rendering for setting the accept attribute.

**Comment by OpenCircleEndy** [comment]
It turns out that it is fairly complex to setup a custom widget. This might be a bit too much for adding just the 'accept' attribute. It might be better to incorporate the EasyUploads component which already has this support built-in: 
[EasyUploads](https://vaadin.com/directory#!addon/easyuploads)
[EasyUploads example](https://github.com/mstahv/easyuploads/blob/master/src/test/java/org/vaadin/easyuploads/demoandtestapp/BasicTest.java#L246)

Added it to the dynamo-vaadin artefact and it seems to do the job. There is also support for a multi-file-upload so Dynamo may also benefit from that.

**Comment by OpenCircleEndy** [comment]
Changed the UploadForm in dynamo-spring to encapsulate the EasyUploads UploadField. Disabled all EasyUploads functionality to preserver the UploadForm functionality as much as possible. Added a showcase for it as well.

**Comment by OpenCircleEndy** [comment]
Integration build succeeded. This will be merged to the upcoming 2.0.0 branch as this functionality might break existing applications in their views with an Upload widget. Would like to have the branch stale for a while as this may be added tot the 1.x release if there is an explicit need for it.
